services:
  webapi:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  tests:
    build:
      context: ./AuthServiceTests
      dockerfile: Dockerfile
    depends_on:
      - webapi
